# Generated by Django 5.0 on 2023-12-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0018_actor_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=models.SlugField(),
        ),
    ]
