# Generated by Django 5.0 on 2023-12-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0020_alter_director_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
